/*
   We can represent a bit pattern of length w=4 with 
   a single hex digit. For a two's complement interpretation
   of these digits, fill in the following table to determine
   the additive inverses of the digits shown:

   0x2 2  --(inverse)-- 0xe 14
   0x3 3  --(inverse)-- 0xd 13
   0x9 9  --(inverse)-- 0x7  7
   0xb 11 --(inverse)-- 0x5  5
   0xc 12 --(inverse)-- 0x4  4

   What do you observe about the bit patterns generated by
   two's complement and unsigned negation?

   : Same, 2^w - x.
*/
